Repository jenkinsci/cloud-stats-plugin, pull requests merged in 2022-11, with the labels that each got.

#30 JENKINS-69966 Fix plugin on 2.375
  .gitignore
  .mvn/extensions.xml
  .mvn/maven.config
  pom.xml
  src/main/resources/org/jenkinsci/plugins/cloudstats/CloudAction/summary.groovy
  src/main/resources/org/jenkinsci/plugins/cloudstats/CloudStatistics/index.groovy
  src/main/resources/org/jenkinsci/plugins/cloudstats/StatsWidget/index.groovy
  src/test/java/org/jenkinsci/plugins/cloudstats/CloudStatisticsTest.java
Labels: bug

#37 Use current spotbugs nullability annotations
  src/main/java/org/jenkinsci/plugins/cloudstats/ActivityIndex.java
  src/main/java/org/jenkinsci/plugins/cloudstats/CloudAction.java
  src/main/java/org/jenkinsci/plugins/cloudstats/CloudStatistics.java
  src/main/java/org/jenkinsci/plugins/cloudstats/CyclicThreadSafeCollection.java
  src/main/java/org/jenkinsci/plugins/cloudstats/Health.java
  src/main/java/org/jenkinsci/plugins/cloudstats/PhaseExecution.java
  src/main/java/org/jenkinsci/plugins/cloudstats/PhaseExecutionAttachment.java
  src/main/java/org/jenkinsci/plugins/cloudstats/ProvisioningActivity.java
  src/main/java/org/jenkinsci/plugins/cloudstats/TrackedPlannedNode.java
  src/test/java/org/jenkinsci/plugins/cloudstats/CloudStatisticsTest.java
  src/test/java/org/jenkinsci/plugins/cloudstats/TrackedAgent.java
Labels: chore

#39 Test on CI with Java 8, Java 11, and Java 17
  Jenkinsfile
Labels: chore

#35 Add spotbugs checks
  pom.xml
  src/spotbugs/excludesFilter.xml
  src/test/java/org/jenkinsci/plugins/cloudstats/CloudStatisticsTest.java
Labels: chore

#38 Enable CD
  .github/dependabot.yml
  .github/release-drafter.yml
  .github/workflows/cd.yaml
  .github/workflows/release-management.yml
  .mvn/maven.config
  pom.xml
Labels: chore

#42 Add markewaite to developers list
  pom.xml
Labels: chore

#44 Use HTTPS SCM URL
  pom.xml
Labels: documentation

#46 Always test with container agents in CI
  Jenkinsfile
Labels: test
